yolov5_path = r'C:\Users\xenes\Documents\dev\yolov5'
model_source = r'C:\Users\xenes\Documents\dev\yolov5\runs\train\exp6\weights\last.pt'
video_source = r'C:\Users\xenes\Documents\dev\iha_programi\Videos\iha_ornek_video.mp4'
logo_source = r'C:\Users\xenes\Documents\dev\iha_programi\gok-tek_logo.png'
searching_for_uav = 'IHA ARANIYOR'
uav_detected = 'IHA TESPIT EDILDI'
chasing_uav = 'IHA TAKIP EDILIYOR'
kirmizi = 0, 0, 255
mavi = 255, 0, 0
yesil = 0, 255, 0
beyaz = 255, 255, 255
siyah = 0, 0, 0
